- name: Chassis
  color: 'bfbe6e'
  description: Chassis SubSystem

- name: Intake
  color: 'b8849c'
  description: Intake SubSystem

- name: Hopper
  color: '222222'
  aliases: Hopper SubSystem

- name: Shooter
  color: '92deb5'
  description: Shooter SubSystem

- name: Climber
  color: '37ec36'
  description: Climber SubSystem

- name: Vision
  color: '31ad50'
  description: Vision SubSystem

- name: System
  color: 'aaaaaa'
  aliases: System

- name: Field
  color: '222222'
  aliases: Field