package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.MountPoseConfigs;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.hardware.Pigeon2;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;

import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.GenericEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.PowerDistribution;
import edu.wpi.first.wpilibj.PowerDistribution.ModuleType;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;

import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants.CANId;
import frc.robot.constants.CommandSwerveDrivetrainConstants;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.utils.Library;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    // Used in DriveRobotRelative
    private final SwerveRequest.RobotCentric robotCentric = new SwerveRequest.RobotCentric();

    RobotConfig config = null;

    private PowerDistribution pdp = new PowerDistribution(CANId.kPDPCanID, ModuleType.kCTRE);
 
    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> setControl(m_translationCharacterization.withVolts(output)),
                    null,
                    this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
            new SysIdRoutine.Config(
                    null, // Use default ramp rate (1 V/s)
                    Volts.of(7), // Use dynamic voltage of 7 V
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    volts -> setControl(m_steerCharacterization.withVolts(volts)),
                    null,
                    this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
            new SysIdRoutine.Config(
                    /* This is in radians per second², but SysId only supports "volts per second" */
                    Volts.of(Math.PI / 6).per(Second),
                    /* This is in radians per second, but SysId only supports "volts" */
                    Volts.of(Math.PI),
                    null, // Use default timeout (10 s)
                    // Log state with SignalLogger class
                    state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
            new SysIdRoutine.Mechanism(
                    output -> {
                        /* output is actually radians per second, but SysId only supports "volts" */
                        setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                        /* also log the requested output for SysId */
                        SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                    },
                    null,
                    this));

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    private final Pigeon2 pigeon = new Pigeon2(TunerConstants.kPigeonId, TunerConstants.kCANBus);

    // Create field and pose related vars
    private final Field2d m_field = new Field2d();

    public Pose2d currPose = null;
    public Rotation2d bearingToHub = null;
    public double distToHub = 0.0;

    private final ShuffleboardTab driveTab = Shuffleboard.getTab("Drive");

    private final GenericEntry sbCurrHeading = driveTab.addPersistent("CurrHeading", 0).withWidget("Text View")
            .withPosition(1, 0).withSize(1, 1).getEntry();
    private final GenericEntry sbBearingToHub = driveTab.addPersistent("BearingToHub", 0).withWidget("Text View")
            .withPosition(2, 0).withSize(1, 1).getEntry();
    private final GenericEntry sbDistToHub = driveTab.addPersistent("DistToHub", 0).withWidget("Text View")
            .withPosition(3, 0).withSize(1, 1).getEntry();

    private final GenericEntry sbYaw = driveTab.addPersistent("Yaw", 0).withWidget("Text View")
            .withPosition(1, 1).withSize(1, 1).getEntry();
    private final GenericEntry sbPitch = driveTab.addPersistent("Pitch", 0).withWidget("Text View")
            .withPosition(2, 1).withSize(1, 1).getEntry();
    private final GenericEntry sbRoll = driveTab.addPersistent("Roll", 0).withWidget("Text View")
            .withPosition(3, 1).withSize(1, 1).getEntry();

    StructPublisher<Pose2d> publisher = NetworkTableInstance.getDefault()
            .getStructTopic("MyPose", Pose2d.struct).publish();

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        m_field.setRobotPose(CommandSwerveDrivetrainConstants.kStartPose);
        SmartDashboard.putData("Field", m_field);

        configPDP();
        configPigeon();
        setupAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        m_field.setRobotPose(CommandSwerveDrivetrainConstants.kStartPose);
        SmartDashboard.putData("Field", m_field);

        configPDP();
        configPigeon();
        setupAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve
     *                                  drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz
     *                                  on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision
     *                                  calculation
     *                                  in the form [x, y, theta]ᵀ, with units in
     *                                  meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation,
                modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        m_field.setRobotPose(CommandSwerveDrivetrainConstants.kStartPose);
        SmartDashboard.putData("Field", m_field);

        configPDP();
        configPigeon();
        setupAutoBuilder();
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                        allianceColor == Alliance.Red
                                ? CommandSwerveDrivetrainConstants.kRedAlliancePerspectiveRotation
                                : CommandSwerveDrivetrainConstants.kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
            });
        }

        bearingToHub = getBearingToHub(); // Update bearing to hub
        sbBearingToHub.setDouble(Library.SBFormat(bearingToHub.getDegrees()));
        sbBearingToHub.setDouble(Library.SBFormat(bearingToHub.getDegrees()));
        distToHub = getDistToHub(); // Update distance to hub
        sbDistToHub.setDouble(Library.SBFormat(distToHub));
        sbCurrHeading.setDouble(Library.SBFormat(getHeading()));
        sbDistToHub.setDouble(Library.SBFormat(distToHub));
        sbCurrHeading.setDouble(Library.SBFormat(getHeading()));

        sbYaw.setDouble(Library.SBFormat(pigeon.getYaw().getValueAsDouble()));
        sbPitch.setDouble(Library.SBFormat(pigeon.getPitch().getValueAsDouble()));
        sbRoll.setDouble(Library.SBFormat(pigeon.getRoll().getValueAsDouble()));
        sbYaw.setDouble(Library.SBFormat(pigeon.getYaw().getValueAsDouble()));
        sbPitch.setDouble(Library.SBFormat(pigeon.getPitch().getValueAsDouble()));
        sbRoll.setDouble(Library.SBFormat(pigeon.getRoll().getValueAsDouble()));

        currPose = getPose();
        m_field.setRobotPose(currPose);
        publisher.set(currPose);
    }

    public ChassisSpeeds getRobotRelativeSpeeds() {
        // Get the current drivetrain state
        var driveState = this.getState(); // This was generated with copilot, i have no faith in this and neither should
                                          // you
        // The state already contains robot-relative ChassisSpeeds
        return driveState.Speeds;
    }

    public void driveRobotRelative(ChassisSpeeds chassisSpeeds) {
        // Convert ChassisSpeeds to a robot-centric swerve request
        setControl(robotCentric
                .withVelocityX(chassisSpeeds.vxMetersPerSecond)
                .withVelocityY(chassisSpeeds.vyMetersPerSecond) // This was generated with copilot, i have no faith in
                                                                // this and neither should you
                .withRotationalRate(chassisSpeeds.omegaRadiansPerSecond));
    }

    private void setupAutoBuilder() {

        try {
            config = RobotConfig.fromGUISettings();
        } catch (Exception e) {
            // Handle exception as needed
            e.printStackTrace();
        }

        // Configure AutoBuilder last
        AutoBuilder.configure(
                this::getPose, // Robot pose supplier
                this::resetPose, // Method to reset odometry (will be called if your auto has a starting pose)
                this::getRobotRelativeSpeeds, // ChassisSpeeds supplier. MUST BE ROBOT RELATIVE
                (speeds, feedforwards) -> driveRobotRelative(speeds), // Method that will drive the robot given ROBOT
                                                                      // RELATIVE ChassisSpeeds. Also optionally outputs
                                                                      // individual module feedforwards
                new PPHolonomicDriveController( // PPHolonomicController is the built in path following controller for
                                                // holonomic drive trains
                        new PIDConstants(
                                CommandSwerveDrivetrainConstants.kTranslationPidP,
                                CommandSwerveDrivetrainConstants.kTranslationPidI,
                                CommandSwerveDrivetrainConstants.kTranslationPidD), // Translation PID constants
                        new PIDConstants(
                                CommandSwerveDrivetrainConstants.kRotationPidP,
                                CommandSwerveDrivetrainConstants.kRotationPidI,
                                CommandSwerveDrivetrainConstants.kRotationPidD) // Rotation PID constants
                ),
                config, // The robot configuration
                () -> {
                    // Boolean supplier that controls when the path will be mirrored for the red
                    // alliance
                    // This will flip the path being followed to the red side of the field.
                    // THE ORIGIN WILL REMAIN ON THE BLUE SIDE

                    var alliance = DriverStation.getAlliance();
                    if (alliance.isPresent()) {
                        return alliance.get() == DriverStation.Alliance.Red;
                    }
                    return false;
                },
                this // Reference to this subsystem to set requirements
        );

    }

    private void configPDP() {
        // Clear sticky faults on the CTRE PDP during startup
        pdp.clearStickyFaults();
    }

    private void configPigeon() {
        // Create a configuration object
        Pigeon2Configuration configs = new Pigeon2Configuration();

        // Configure the mount pose to match the physical orientation on the robot.
        // The values here represent the axis that points forward/up/left in the robot's
        // reference frame.
        configs.MountPose = new MountPoseConfigs()
                .withMountPoseYaw(-90.0) // Degrees offset for Yaw
                .withMountPosePitch(90.0) // Degrees offset for Pitch
                .withMountPoseRoll(0.0); // Degrees offset for Roll

        // Apply the configurations to the device
        StatusCode status = pigeon.getConfigurator().apply(configs);

        if (status.isOK()) {
            System.out.println("Pigeon 2 configuration applied successfully!");
        } else {
            System.err.println("Failed to apply Pigeon 2 configuration: " + status.toString());
        }

        // Set initial yaw based on alliance side
        // Blue alliance: 0° (facing red alliance wall)
        // Red alliance: 180° (facing blue alliance wall)
        setYawBasedOnAlliance();
    }

    /**
     * Sets the Pigeon yaw based on the current alliance.
     * This should be called during initialization and when alliance changes.
     * Blue alliance: 0° (forward is toward red wall)
     * Red alliance: 180° (forward is toward blue wall)
     */
    public void setYawBasedOnAlliance() {
        Optional<Alliance> alliance = DriverStation.getAlliance();
        
        if (alliance.isPresent()) {
            if (alliance.get() == Alliance.Red) {
                pigeon.setYaw(180.0);
                System.out.println("Pigeon yaw set to 180° for Red Alliance");
            } else {
                pigeon.setYaw(0.0);
                System.out.println("Pigeon yaw set to 0° for Blue Alliance");
            }
        } else {
            // Default to blue alliance if not connected to FMS
            pigeon.setYaw(0.0);
            System.out.println("Alliance not available - defaulting Pigeon yaw to 0° (Blue Alliance)");
        }
    }

    public PowerDistribution getPDP() {
        return pdp;
    }

    public Pose2d getPose() {
        return getStateCopy().Pose;
    }

    public Rotation2d getBearingToHub() {
        return ((getPose().getTranslation().minus(CommandSwerveDrivetrainConstants.kHubPose.getTranslation())).getAngle().plus(new Rotation2d(Math.PI)));
    }

    public double getDistToHub() {
        return CommandSwerveDrivetrainConstants.kHubPose.getTranslation().getDistance(getPose().getTranslation());
    }

    public double getHeading() {
        return pigeon.getYaw().getValueAsDouble();
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(CommandSwerveDrivetrainConstants.kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
